grails:
   profile: plugin
   doc:
      authors: 'Antony Jones, Matt Tortolani, Tomas Lin, Marcin Erdmann'
      license: 'Apache License 2.0'
      title:   'Feature Switch Plugin'
info:
   app:
      name: '@info.app.name@'
      version: '@info.app.version@'
      grailsVersion: '@info.app.grailsVersion@'
